[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"

chain_id = 5
# remappings = ["@openzeppelin/=lib/openzeppelin-contracts/","@v3-core/=lib/v3-core/" ,"@v3-periphery/=lib/v3-periphery/" ,"@chainlink/=lib/chainlink/", "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/", "@chiruLabs/=lib/ERC721A-Upgradeable"]

[rpc_endpoints]
goerli = "PlaceYourRpc"

[etherscan]
goerli = { key = "${GOERLI_KEY}" }